name: Dealivery CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. GitHub 레포지토리 체크아웃
      - name: Checkout sources
        uses: actions/checkout@v4

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew clean bootJar

      # 4. EC2 서버에 파일 전송
      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "backend/build/libs/backend-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/"

      # 5. Spring 애플리케이션 재시작
      - name: Restart Spring project
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 15m
          script: |
            if lsof -i:8080; then
              echo "8080 포트에서 실행 중인 프로세스 종료 중..."
              PID=$(lsof -t -i:8080)  # 8080 포트를 사용하는 프로세스의 PID를 가져옴
              if [ -n "$PID" ]; then
                echo "8080 포트에서 실행 중인 프로세스(PID: $PID) 종료 중..."
                kill -9 "$PID" || true  # 프로세스를 강제로 종료
                sleep 15
              else
                echo "종료할 프로세스를 찾지 못했습니다."
              fi
            fi

            nohup bash -c "source /home/ubuntu/.env && export $(cat /home/ubuntu/.env | xargs) && java -jar backend/build/libs/backend-0.0.1-SNAPSHOT.jar" > application.log 2>&1 &

